"use client";

import { useState, useEffect, useCallback } from "react";

/**
 * 매매 일지 템플릿
 * - 3 섹션: 진입 계획 / 실행 결과 / 회고
 * - LocalStorage 자동 저장 (실수로 닫아도 복원)
 * - Markdown 복사 / 인쇄(PDF) / 초기화
 */

const STORAGE_KEY = "victor-alpha-trade-journal-draft";

type Form = {
  // Plan
  date: string;
  asset: string;
  side: "long" | "short";
  setupName: string;
  thesis: string;
  entry: string;
  stop: string;
  target: string;
  oneRAmount: string;
  qty: string;
  leverage: string;
  marketContext: string;
  checklistPassed: "yes" | "no" | "partial";
  // Execute
  exitPrice: string;
  exitReason: "target" | "stop" | "trail" | "time" | "discretion" | "";
  pnlR: string;
  pnlAbs: string;
  holdMinutes: string;
  // Review
  followedSystem: "yes" | "no" | "partial";
  systemBreach: string;
  emotionScore: string;
  lessons: string;
  nextTime: string;
};

const today = () => new Date().toISOString().slice(0, 16);

const blank: Form = {
  date: "",
  asset: "",
  side: "long",
  setupName: "",
  thesis: "",
  entry: "",
  stop: "",
  target: "",
  oneRAmount: "",
  qty: "",
  leverage: "1",
  marketContext: "",
  checklistPassed: "yes",
  exitPrice: "",
  exitReason: "",
  pnlR: "",
  pnlAbs: "",
  holdMinutes: "",
  followedSystem: "yes",
  systemBreach: "",
  emotionScore: "3",
  lessons: "",
  nextTime: "",
};

export function TradeJournal() {
  const [form, setForm] = useState<Form>(blank);
  const [hydrated, setHydrated] = useState(false);
  const [copied, setCopied] = useState<"md" | "table" | null>(null);

  // Hydrate from localStorage
  useEffect(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const parsed = JSON.parse(raw) as Partial<Form>;
        setForm((f) => ({ ...f, ...parsed }));
      } else {
        setForm((f) => ({ ...f, date: today() }));
      }
    } catch {
      // ignore
    }
    setHydrated(true);
  }, []);

  // Auto-save to localStorage
  useEffect(() => {
    if (!hydrated) return;
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(form));
    } catch {
      // ignore (quota etc.)
    }
  }, [form, hydrated]);

  const set = <K extends keyof Form>(key: K, val: Form[K]) =>
    setForm((f) => ({ ...f, [key]: val }));

  const reset = () => {
    if (!confirm("일지를 초기화할까요? 현재 내용은 사라집니다.")) return;
    setForm({ ...blank, date: today() });
  };

  const buildMarkdown = useCallback(() => {
    const exitReasonLabel = {
      target: "목표 도달",
      stop: "손절",
      trail: "트레일링 스탑",
      time: "시간 만료",
      discretion: "재량 청산",
      "": "—",
    }[form.exitReason];

    const sideLabel = form.side === "long" ? "🟢 Long" : "🔴 Short";
    const checklistLabel = {
      yes: "통과",
      partial: "일부 통과",
      no: "미통과",
    }[form.checklistPassed];
    const systemLabel = {
      yes: "준수",
      partial: "일부 위반",
      no: "위반",
    }[form.followedSystem];

    return `# 매매 일지 — ${form.asset || "(자산)"} · ${form.date}

## ① 진입 계획

- **자산**: ${form.asset || "—"}
- **방향**: ${sideLabel}
- **셋업**: ${form.setupName || "—"}
- **진입 근거**:
${form.thesis ? form.thesis.split("\n").map((l) => `  > ${l}`).join("\n") : "  > —"}
- **진입가**: ${form.entry || "—"}
- **손절가**: ${form.stop || "—"}
- **목표가**: ${form.target || "—"}
- **1R 금액**: ${form.oneRAmount || "—"}
- **수량**: ${form.qty || "—"}
- **레버리지**: ${form.leverage || "1"}×
- **시장 환경**: ${form.marketContext || "—"}
- **진입 전 체크리스트**: ${checklistLabel}

## ② 실행 결과

- **청산가**: ${form.exitPrice || "—"}
- **청산 사유**: ${exitReasonLabel}
- **손익(R)**: ${form.pnlR || "—"}R
- **손익(절대)**: ${form.pnlAbs || "—"}
- **보유 시간**: ${form.holdMinutes || "—"}분

## ③ 회고

- **시스템 준수**: ${systemLabel}
- **시스템 위반 항목**: ${form.systemBreach || "—"}
- **감정 점수(1~5)**: ${form.emotionScore || "—"} / 5
- **학습 포인트**:
${form.lessons ? form.lessons.split("\n").map((l) => `  - ${l}`).join("\n") : "  - —"}
- **다음에 같은 셋업이면**:
${form.nextTime ? form.nextTime.split("\n").map((l) => `  - ${l}`).join("\n") : "  - —"}

---
*Generated by Victor Alpha — Trading Desk Journal*
`;
  }, [form]);

  const buildTable = useCallback(() => {
    const sideLabel = form.side === "long" ? "Long" : "Short";
    return `| 날짜 | 자산 | 방향 | 셋업 | 진입 | 손절 | 목표 | 청산 | 손익(R) | 보유(분) | 시스템 | 감정 |
|---|---|---|---|---|---|---|---|---|---|---|---|
| ${form.date} | ${form.asset} | ${sideLabel} | ${form.setupName} | ${form.entry} | ${form.stop} | ${form.target} | ${form.exitPrice} | ${form.pnlR}R | ${form.holdMinutes} | ${form.followedSystem} | ${form.emotionScore}/5 |`;
  }, [form]);

  const copyMd = async () => {
    try {
      await navigator.clipboard.writeText(buildMarkdown());
      setCopied("md");
      setTimeout(() => setCopied(null), 1800);
    } catch {
      alert("복사 실패. 브라우저가 클립보드를 차단했을 수 있습니다.");
    }
  };

  const copyTable = async () => {
    try {
      await navigator.clipboard.writeText(buildTable());
      setCopied("table");
      setTimeout(() => setCopied(null), 1800);
    } catch {
      alert("복사 실패.");
    }
  };

  const print = () => window.print();

  if (!hydrated) {
    return (
      <div className="rounded-md border border-border bg-surface p-8 text-center text-fg-muted">
        불러오는 중…
      </div>
    );
  }

  return (
    <div className="space-y-10">
      {/* ① Plan ───────────────────────────────────── */}
      <section className="rounded-md border border-border bg-surface p-6">
        <header className="mb-5 flex items-baseline justify-between">
          <h2 className="font-display text-xl font-bold tracking-tight">
            ① 진입 계획
          </h2>
          <p className="font-mono text-[11px] uppercase tracking-wider text-fg-muted">
            진입 직전 작성
          </p>
        </header>

        <div className="grid gap-4 md:grid-cols-2">
          <Field
            label="날짜·시각"
            type="datetime-local"
            value={form.date}
            onChange={(v) => set("date", v)}
          />
          <Field
            label="자산·심볼"
            placeholder="BTC/USDT, KOSPI, NQ1!"
            value={form.asset}
            onChange={(v) => set("asset", v)}
          />
          <div className="md:col-span-2">
            <label className="block text-meta font-semibold text-fg">
              방향
            </label>
            <div className="mt-1.5 flex gap-2">
              <button
                type="button"
                onClick={() => set("side", "long")}
                className={`flex-1 rounded-md border px-3 py-2 text-sm font-semibold ${
                  form.side === "long"
                    ? "border-up bg-up/10 text-up"
                    : "border-border bg-bg text-fg-muted hover:border-accent"
                }`}
              >
                🟢 Long
              </button>
              <button
                type="button"
                onClick={() => set("side", "short")}
                className={`flex-1 rounded-md border px-3 py-2 text-sm font-semibold ${
                  form.side === "short"
                    ? "border-down bg-down/10 text-down"
                    : "border-border bg-bg text-fg-muted hover:border-accent"
                }`}
              >
                🔴 Short
              </button>
            </div>
          </div>
          <Field
            label="셋업 이름"
            placeholder="RSI50 + EMA200 추세, 박스권 돌파 등"
            value={form.setupName}
            onChange={(v) => set("setupName", v)}
          />
          <Field
            label="시장 환경"
            placeholder="추세 / 횡보 / 변동성 ↑ / 매크로 이벤트 임박 등"
            value={form.marketContext}
            onChange={(v) => set("marketContext", v)}
          />
          <div className="md:col-span-2">
            <Textarea
              label="진입 근거"
              placeholder="이 셋업이 왜 작동한다고 판단했는가. 차트 구조·지표·환경 정합성 3~5줄."
              value={form.thesis}
              onChange={(v) => set("thesis", v)}
              rows={4}
            />
          </div>
          <Field
            label="진입가"
            value={form.entry}
            onChange={(v) => set("entry", v)}
          />
          <Field
            label="손절가"
            hint={form.side === "long" ? "진입가보다 아래" : "진입가보다 위"}
            value={form.stop}
            onChange={(v) => set("stop", v)}
          />
          <Field
            label="목표가"
            hint={form.side === "long" ? "진입가보다 위" : "진입가보다 아래"}
            value={form.target}
            onChange={(v) => set("target", v)}
          />
          <Field
            label="레버리지"
            value={form.leverage}
            onChange={(v) => set("leverage", v)}
            suffix={<span className="text-meta text-fg-muted">×</span>}
          />
          <Field
            label="1R 금액 (최대 손실 한도)"
            value={form.oneRAmount}
            onChange={(v) => set("oneRAmount", v)}
          />
          <Field
            label="수량 / 계약 수"
            value={form.qty}
            onChange={(v) => set("qty", v)}
          />
          <div className="md:col-span-2">
            <label className="block text-meta font-semibold text-fg">
              진입 전 체크리스트 통과 여부
            </label>
            <div className="mt-1.5 flex gap-2">
              {(
                [
                  ["yes", "✓ 통과", "border-up bg-up/10 text-up"],
                  ["partial", "△ 일부", "border-warning bg-warning/10 text-warning"],
                  ["no", "✗ 미통과", "border-down bg-down/10 text-down"],
                ] as const
              ).map(([val, label, sel]) => (
                <button
                  key={val}
                  type="button"
                  onClick={() => set("checklistPassed", val)}
                  className={`flex-1 rounded-md border px-3 py-2 text-sm font-semibold ${
                    form.checklistPassed === val
                      ? sel
                      : "border-border bg-bg text-fg-muted hover:border-accent"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ② Execute ────────────────────────────────── */}
      <section className="rounded-md border border-border bg-surface p-6">
        <header className="mb-5 flex items-baseline justify-between">
          <h2 className="font-display text-xl font-bold tracking-tight">
            ② 실행 결과
          </h2>
          <p className="font-mono text-[11px] uppercase tracking-wider text-fg-muted">
            청산 직후 작성
          </p>
        </header>

        <div className="grid gap-4 md:grid-cols-2">
          <Field
            label="청산가"
            value={form.exitPrice}
            onChange={(v) => set("exitPrice", v)}
          />
          <div>
            <label className="block text-meta font-semibold text-fg">
              청산 사유
            </label>
            <select
              value={form.exitReason}
              onChange={(e) => set("exitReason", e.target.value as Form["exitReason"])}
              className="mt-1.5 w-full rounded-md border border-border bg-surface px-3 py-2 font-serif-body text-[15px] outline-none focus:border-accent"
            >
              <option value="">—</option>
              <option value="target">목표 도달</option>
              <option value="stop">손절</option>
              <option value="trail">트레일링 스탑</option>
              <option value="time">시간 만료</option>
              <option value="discretion">재량 청산</option>
            </select>
          </div>
          <Field
            label="손익 (R 단위)"
            placeholder="+1.8 또는 -1.0"
            value={form.pnlR}
            onChange={(v) => set("pnlR", v)}
            suffix={<span className="text-meta text-fg-muted">R</span>}
          />
          <Field
            label="손익 (절대 금액)"
            placeholder="+150 USDT"
            value={form.pnlAbs}
            onChange={(v) => set("pnlAbs", v)}
          />
          <Field
            label="보유 시간 (분)"
            value={form.holdMinutes}
            onChange={(v) => set("holdMinutes", v)}
            suffix={<span className="text-meta text-fg-muted">min</span>}
          />
        </div>
      </section>

      {/* ③ Review ─────────────────────────────────── */}
      <section className="rounded-md border border-border bg-surface p-6">
        <header className="mb-5 flex items-baseline justify-between">
          <h2 className="font-display text-xl font-bold tracking-tight">
            ③ 회고
          </h2>
          <p className="font-mono text-[11px] uppercase tracking-wider text-fg-muted">
            청산 후 5분 / 당일 마감 시
          </p>
        </header>

        <div className="space-y-4">
          <div>
            <label className="block text-meta font-semibold text-fg">
              시스템대로 매매했나
            </label>
            <div className="mt-1.5 flex gap-2">
              {(
                [
                  ["yes", "✓ 준수", "border-up bg-up/10 text-up"],
                  ["partial", "△ 일부 위반", "border-warning bg-warning/10 text-warning"],
                  ["no", "✗ 위반", "border-down bg-down/10 text-down"],
                ] as const
              ).map(([val, label, sel]) => (
                <button
                  key={val}
                  type="button"
                  onClick={() => set("followedSystem", val)}
                  className={`flex-1 rounded-md border px-3 py-2 text-sm font-semibold ${
                    form.followedSystem === val
                      ? sel
                      : "border-border bg-bg text-fg-muted hover:border-accent"
                  }`}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          <Textarea
            label="시스템 위반이라면 어디서"
            placeholder="예: 손절을 임의로 옮겼다 / 체크리스트 미통과인데 진입했다 / 사이즈를 평소의 2배로 했다"
            value={form.systemBreach}
            onChange={(v) => set("systemBreach", v)}
            rows={2}
          />

          <div>
            <label className="block text-meta font-semibold text-fg">
              감정 상태 (1~5)
            </label>
            <p className="mt-1 text-[12px] text-fg-muted">
              1 = 시스템적 / 5 = 감정에 흔들림
            </p>
            <div className="mt-2 flex gap-2">
              {[1, 2, 3, 4, 5].map((n) => (
                <button
                  key={n}
                  type="button"
                  onClick={() => set("emotionScore", String(n))}
                  className={`flex-1 rounded-md border px-3 py-2 text-sm font-semibold ${
                    form.emotionScore === String(n)
                      ? n <= 2
                        ? "border-up bg-up/10 text-up"
                        : n === 3
                          ? "border-warning bg-warning/10 text-warning"
                          : "border-down bg-down/10 text-down"
                      : "border-border bg-bg text-fg-muted hover:border-accent"
                  }`}
                >
                  {n}
                </button>
              ))}
            </div>
          </div>

          <Textarea
            label="학습 포인트 (3줄 권장)"
            placeholder={"무엇을 새로 알게 됐는가\n무엇이 잘 됐는가\n무엇이 안 됐는가"}
            value={form.lessons}
            onChange={(v) => set("lessons", v)}
            rows={4}
          />

          <Textarea
            label="다음에 같은 셋업이면 무엇을 다르게 할까"
            placeholder="구체적 행동 변화 한두 가지"
            value={form.nextTime}
            onChange={(v) => set("nextTime", v)}
            rows={3}
          />
        </div>
      </section>

      {/* Actions ─────────────────────────────────── */}
      <section className="sticky bottom-4 z-10 rounded-md border border-border bg-surface-warm p-4 shadow-sm print:hidden">
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            onClick={copyMd}
            className="rounded-md bg-accent px-4 py-2 text-pill text-white hover:bg-accent-hover"
          >
            {copied === "md" ? "✓ 복사됨" : "Markdown 복사"}
          </button>
          <button
            type="button"
            onClick={copyTable}
            className="rounded-md border border-ink px-4 py-2 text-pill text-fg hover:border-accent"
          >
            {copied === "table" ? "✓ 복사됨" : "표 한 줄 복사"}
          </button>
          <button
            type="button"
            onClick={print}
            className="rounded-md border border-ink px-4 py-2 text-pill text-fg hover:border-accent"
          >
            인쇄 / PDF
          </button>
          <button
            type="button"
            onClick={reset}
            className="ml-auto rounded-md border border-border px-4 py-2 text-pill text-fg-muted hover:border-down hover:text-down"
          >
            초기화
          </button>
        </div>
        <p className="mt-2 text-[12px] text-fg-muted">
          입력값은 자동으로 브라우저에 저장됩니다 (이 기기에서만). 페이지를 닫아도
          복원됩니다.
        </p>
      </section>
    </div>
  );
}

function Field({
  label,
  hint,
  value,
  onChange,
  type = "text",
  placeholder,
  suffix,
}: {
  label: string;
  hint?: string;
  value: string;
  onChange: (v: string) => void;
  type?: string;
  placeholder?: string;
  suffix?: React.ReactNode;
}) {
  return (
    <div>
      <label className="block text-meta font-semibold text-fg">{label}</label>
      {hint && <p className="text-[12px] text-fg-muted">{hint}</p>}
      <div className="mt-1.5 flex items-center gap-2 rounded-md border border-border bg-surface focus-within:border-accent">
        <input
          type={type}
          value={value}
          placeholder={placeholder}
          onChange={(e) => onChange(e.target.value)}
          className="w-full bg-transparent px-3 py-2 font-serif-body text-[15px] outline-none"
        />
        {suffix && <div className="pr-3">{suffix}</div>}
      </div>
    </div>
  );
}

function Textarea({
  label,
  placeholder,
  value,
  onChange,
  rows = 3,
}: {
  label: string;
  placeholder?: string;
  value: string;
  onChange: (v: string) => void;
  rows?: number;
}) {
  return (
    <div>
      <label className="block text-meta font-semibold text-fg">{label}</label>
      <textarea
        rows={rows}
        value={value}
        placeholder={placeholder}
        onChange={(e) => onChange(e.target.value)}
        className="mt-1.5 w-full break-keep rounded-md border border-border bg-surface px-3 py-2 font-serif-body text-[15px] leading-[1.6] outline-none focus:border-accent"
      />
    </div>
  );
}
